services:

  database:
    image: mysql:8.4
    restart: unless-stopped
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: traccar
      MYSQL_USER: traccar
      MYSQL_PASSWORD: traccar
    volumes:
      - ./local-data/mysql/data:/var/lib/mysql

  redis:
    image: redis:latest
    restart: unless-stopped
    command: redis-server --requirepass ABC123mysql --appendonly no --save "" --io-threads 15 --io-threads-do-reads yes --maxmemory 1gb --maxmemory-policy allkeys-lru --lazyfree-lazy-eviction yes --lazyfree-lazy-expire yes --lazyfree-lazy-server-del yes --replica-lazy-flush yes --lazyfree-lazy-user-del yes --lazyfree-lazy-user-flush yes
    ports:
      - "6379:6379"

  traccar-primary:
    image: traccar:5b6c748-1.0.1
    restart: unless-stopped
    depends_on:
      - database
      - redis
    environment:
      CONFIG_USE_ENVIRONMENT_VARIABLES: "true"
      DATABASE_DRIVER: com.mysql.cj.jdbc.Driver
      DATABASE_URL: >-
        jdbc:mysql://database:3306/traccar
        ?zeroDateTimeBehavior=round
        &serverTimezone=UTC
        &allowPublicKeyRetrieval=true
        &useSSL=false
        &allowMultiQueries=true
        &autoReconnect=true
        &useUnicode=yes
        &characterEncoding=UTF-8
        &sessionVariables=sql_mode=''
      DATABASE_USER: traccar
      DATABASE_PASSWORD: traccar
      BROADCAST_TYPE : redis
      BROADCAST_ADDRESS : redis://:ABC123mysql@redis:6379
      SERVER_BUFFERING_THRESHOLD : 0
    healthcheck:
      test: [ "CMD", "wget", "-q", "--spider", "http://localhost:8082/api/health" ]
      interval: 2m
      timeout: 5s
      start_period: 1h
      retries: 3
    ports:
      - "8082:8082"
      - "5055:5055"
    volumes:
      - ./local-data/mysql/traccar-primary/logs:/opt/traccar/logs

  traccar-secondary:
    image: traccar:5b6c748-1.0.1
    restart: unless-stopped
    depends_on:
      - database
      - redis
    environment:
      CONFIG_USE_ENVIRONMENT_VARIABLES: "true"
      DATABASE_DRIVER: com.mysql.cj.jdbc.Driver
      DATABASE_URL: >-
        jdbc:mysql://database:3306/traccar
        ?zeroDateTimeBehavior=round
        &serverTimezone=UTC
        &allowPublicKeyRetrieval=true
        &useSSL=false
        &allowMultiQueries=true
        &autoReconnect=true
        &useUnicode=yes
        &characterEncoding=UTF-8
        &sessionVariables=sql_mode=''
      DATABASE_USER: traccar
      DATABASE_PASSWORD: traccar
      BROADCAST_TYPE : redis
      BROADCAST_ADDRESS : redis://:ABC123mysql@redis:6379
      SERVER_BUFFERING_THRESHOLD : 0
    healthcheck:
      test: [ "CMD", "wget", "-q", "--spider", "http://localhost:8082/api/health" ]
      interval: 2m
      timeout: 5s
      start_period: 1h
      retries: 3
    ports:
      - "8083:8082"
    volumes:
      - ./local-data/mysql/traccar-secondary/logs:/opt/traccar/logs

  autoheal:
    image: willfarrell/autoheal:latest
    restart: always
    environment:
      AUTOHEAL_CONTAINER_LABEL: all
      AUTOHEAL_INTERVAL: 60
      AUTOHEAL_START_PERIOD: 3600
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
